version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: my_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: breach
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - my_db_volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  my_db_volume:
